# Mysql数据库连接配置: com.mysql.cj.jdbc.Driver
spring:
  datasource:
    url: jdbc:mysql://49.232.146.162:3306/natsume?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  flyway:
    enabled: false
  redis:
    host: 49.232.146.162
    port: 6379
    password: password
  rabbitmq:
    addresses: 49.232.146.162
    port: 5672
    username: guest
    password: guest

# mybatis配置
mybatis:
  configuration:
    #开启驼峰命名匹配映射
    map-underscore-to-camel-case: true
    # 控制台日志配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #配置mybatis的xml映射配置文件路径
  mapper-locations: classpath:mapper/*.xml
  #配置mybatis映射配置文件中实体类别名
  type-aliases-package: com.natsume.entity


# pagehelper 配置
pagehelper:
  auto-dialect: true
  reasonable: true
  support-methods-arguments: true
  params: countSql



server:
  servlet:
    session:
      timeout: 1200 # s

  port: 8081
