# Mysql数据库连接配置: com.mysql.cj.jdbc.Driver
spring:
  datasource:
    url: jdbc:mysql://49.232.146.162:3306/natsume?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: U2FsdGVkX18kY9pA6bwGYP/4xavO576XOCjgKjQbL48=
    driver-class-name: com.mysql.jdbc.Driver
  flyway:
    enabled: false
  redis:
    host: 123.207.218.247
    port: 6379
    password: password
  rabbitmq:
    addresses: 123.207.218.247
    port: 5672
    username: guest
    password: guest

# mybatis配置
mybatis:
  configuration:
    #开启驼峰命名匹配映射
    map-underscore-to-camel-case: true
    # 控制台日志配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #配置mybatis的xml映射配置文件路径
  mapper-locations: classpath:mapper/*.xml
  #配置mybatis映射配置文件中实体类别名
  type-aliases-package: com.natsume.entity

wx:
  appId: wx18cb444312117ba8
  mchKey: d743bf233156d3c019c7d5f732f860ff
  openIdUrl: https://api.weixin.qq.com/sns/jscode2session

# pagehelper 配置
pagehelper:
  auto-dialect: true
  reasonable: true
  support-methods-arguments: true
  params: countSql

# 定时任务配置
scheduled:
  week:
    fixedRate: 600000 # ms, 10 min
    interval: 10
    cron: "0 */30 * * * ?"  # 30 min

server:
  servlet:
    session:
      timeout: 1800 # s

