# Mysql数据库连接配置: com.mysql.cj.jdbc.Driver
spring:
  datasource:
    url: jdbc:mysql://49.232.146.162:3306/natsume?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: U2FsdGVkX18kY9pA6bwGYP/4xavO576XOCjgKjQbL48=
    driver-class-name: com.mysql.jdbc.Driver
  flyway:
    enabled: false
  redis:
    host: 123.207.218.247
    port: 6379
    password: password
  rabbitmq:
    addresses: 123.207.218.247
    port: 5672
    username: guest
    password: guest

# mybatis配置
mybatis:
  configuration:
    #开启驼峰命名匹配映射
    map-underscore-to-camel-case: true
    # 控制台日志配置
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #配置mybatis的xml映射配置文件路径
  mapper-locations: classpath:mapper/*.xml
  #配置mybatis映射配置文件中实体类别名
  type-aliases-package: com.natsumes.entity

wx:
  appId: wx4979619f65fe08f5
  mchKey: 99a984c7045f09c7ac0d49a92598b5eb
  openIdUrl: https://api.weixin.qq.com/sns/jscode2session

# pagehelper 配置
pagehelper:
  auto-dialect: true
  reasonable: true
  support-methods-arguments: true
  params: countSql
  rowBoundsWithCount: true

server:
  servlet:
    session:
      timeout: 120000 # s

